# Generated by Django 3.2.25 on 2025-03-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACHINE_ID', models.IntegerField()),
                ('LINE_NUMB', models.IntegerField()),
                ('OPERATOR_ID', models.CharField(max_length=30)),
                ('DATE', models.DateField()),
                ('START_TIME', models.TimeField()),
                ('END_TIME', models.TimeField()),
                ('MODE', models.IntegerField()),
                ('STITCH_COUNT', models.IntegerField()),
                ('NEEDLE_RUNTIME', models.FloatField()),
                ('NEEDLE_STOPTIME', models.FloatField()),
                ('Tx_LOGID', models.IntegerField()),
                ('Str_LOGID', models.IntegerField()),
                ('DEVICE_ID', models.IntegerField()),
                ('RESERVE', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('MACHINE_ID', 'OPERATOR_ID', 'DATE', 'START_TIME', 'END_TIME')},
            },
        ),
    ]
